# syntax=docker/dockerfile:1

## Build
FROM golang:1.19-alpine AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . ./

RUN go build -o /go-save-rabbit

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /go-save-rabbit /go-save-rabbit

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/go-save-rabbit"]
